import { Box, Heading, Text, Grid, GridItem, Link as ChakraLink } from '@chakra-ui/react'
import type { NextPage } from "next";
import Head from 'next/head'
import Link from 'next/link'

const Templates: NextPage = () => {
    return (
        <>
            <Head>
                <title>PPBL Summer 2022</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Box w="60%" mx="auto">
                <Heading>Templates for each rendering method in Next.js</Heading>
                <Grid templateColumns='repeat(2, 1fr)' gap='3' pt='5'>
                    <GridItem bg='blue.100' _hover={{bg: 'blue.800', color: 'white'}}>
                        <Text p='3'>
                            <Link href="/templates/ssg">Static Site Generation</Link>
                        </Text>
                    </GridItem>
                    <GridItem bg='blue.100' _hover={{bg: 'blue.800', color: 'white'}}>
                        <Text p='3'>
                            <Link href="/templates/isr">Incremental Site Rendering</Link>
                        </Text>
                    </GridItem>
                    <GridItem bg='blue.100' _hover={{bg: 'blue.800', color: 'white'}}>
                        <Text p='3'>
                            <Link href="/templates/ssr">Server-Side Rendering</Link>
                        </Text>
                    </GridItem>
                    <GridItem bg='blue.100' _hover={{bg: 'blue.800', color: 'white'}}>
                        <Text p='3'>
                            <Link href="/templates/csr">Client Side Rendering</Link>
                        </Text>
                    </GridItem>
                    <GridItem bg='orange.100' colSpan={2}>
                        <Text p='3'>
                            If you are new to data queries on NextJS, we recommend that you start by <ChakraLink href="https://blog.logrocket.com/why-use-next-js-apollo/">reading this tutorial</ChakraLink>. Then, check out the <ChakraLink href="">official documentation from NextJS</ChakraLink>. As always, bring your questions to Live Coding on Wednesdays and Thursdays at 1430 UTC, or reach out for help on Discord.
                        </Text>
                    </GridItem>
                </Grid>
            </Box>
        </>
    )
}

export default Templates